pipeline:
  backend:
    image: ${PKG_OS}
    environment:
      - GOOS=linux
    commands:
      - git branch
      - git log
      - ls -la
      - pwd
      - env
      - export

  # windows_build:
    # image: naviot/scalarizr-build-${PKG_OS}

matrix:
  include:
    - PKG_OS: windows
      OS_VERSION: last
