pipeline:  
  windows-build:
    group: build
    image: naviot/scalarizr-build-windows
    commands:
      - ls -la
      - pwd
      - rm -rf /ci; git clone -b master --single-branch git@github.com:Scalr/ci.git /ci
      - sleep 10
    when:
      matrix:
        OS_NAME: windows

  centos-build:
    group: build
    image: centos
    commands:
      - export
      - env
      - sleep 10
    when:
      matrix:
        OS_NAME: centos

  ubuntu-build:
    group: build
    image: ubuntu
    commands:
      - export
      - env
      - sleep 10
    when:
      matrix:
        OS_NAME: ubuntu

matrix:
  include:
    - OS_NAME: windows
      OS_VERSION: last
    - OS_NAME: centos
      OS_VERSION: 6.7
      OS_ARCH: x86
    - OS_NAME: ubuntu
      OS_VERSION: 14.04
      OS_ARCH: x32
