pipeline:  
  windows-build:
    image: naviot/scalarizr-build-windows
    group: build
    environment:
      - OMNIBUS_PROJECT = scalarizr
    commands:
      - ls -la
      - pwd
      - rm -rf /ci; git clone -b new-drone-ci --single-branch git@github.com:Scalr/ci.git /ci
      - python3 /ci/python/windows.py

  centos-build:
    image: centos
    group: build
    commands:
      - export
      - env
      - sleep 3

  ubuntu-build:
    image: ubuntu
    group: build
    commands:
      - export
      - env
      - sleep 3

  ubuntu-build1:
    image: ubuntu
    commands:
      - export
      - env
      - sleep 3

