pipeline:  
  windows-build:
    image: naviot/scalarizr-build-windows
    group: build
    environment:
      - OMNIBUS_PROJECT=scalarizr
      - CI_DIR=/ci
      - BUILDER=python3 /ci/python/builder.py
    commands:
      - export
      - rm -rf $CI_DIR; git clone -b new-drone-ci --single-branch git@github.com:Scalr/ci.git $CI_DIR
      - export SCALARIZR_BUILD_VERSION='5.7.2.3222'
      - python3 $CI_DIR/python/windows.py

  centos-build:
    image: centos
    group: build
    commands:
      - export
      - env
      - sleep 3

  ubuntu-build:
    image: ubuntu
    group: build
    commands:
      - export
      - env
      - sleep 3

  ubuntu-build1:
    image: ubuntu
    commands:
      - export
      - env
      - sleep 3

