pipeline:  
  windows-build:
    image: naviot/scalarizr-build-windows
    group: build
    commands:
      - ls -la
      - pwd
      - rm -rf /ci; git clone -b master --single-branch git@github.com:Scalr/ci.git /ci
      - sleep 10
    when:
      matrix:
        OS_NAME: windows

  centos-build:
    image: centos
    group: build
    commands:
      - export
      - env
      - sleep 10
    when:
      matrix:
        OS_NAME: centos

  ubuntu-build:
    image: ubuntu
    group: build
    commands:
      - export
      - env
      - sleep 10
    when:
      matrix:
        OS_NAME: ubuntu

  ubuntu-build1:
    image: ubuntu
    commands:
      - export
      - env
      - sleep 10
    when:
      matrix:
        OS_NAME: ubuntu

