#!/bin/bash
#
# Perform necessary scalarizr removal steps
# after package is uninstalled.
#

if [ "$1" = '1' ] || [ "$1" = 'upgrade' ]; then
    echo "scalarizr has been upgraded!"
else
    [ -f /etc/init.d/scalarizr ] && unlink /etc/init.d/scalarizr
    [ -f /etc/init.d/scalr-upd-client ] && unlink /etc/init.d/scalr-upd-client
    [ -f /lib/systemd/system/scalarizr.service ] && unlink /lib/systemd/system/scalarizr.service
    [ -f /lib/systemd/system/scalr-upd-client.service ] && unlink /lib/systemd/system/scalr-upd-client.service
    [ -f /lib/systemd/system/scalarizr-shutdown.service ] && unlink /lib/systemd/system/scalarizr-shutdown.service
    # if ! dpkg -l scalr-upd-client; then  # scalarizr >= 0.9, <= 0.21
    #     unlink /etc/init.d/scalr-upd-client
    # fi
    echo "scalarizr has been uninstalled!"
fi

exit 0
